#!/bin/bash
# Get all merged branches except the current one, which is starred.
set -x
branches=$(git branch --merge | grep -v '^\*')
for branch in $branches; do
    git branch -d "$branch"
done
git co master
