# This file is part of OpenHatch.
# Copyright (C) 2009 OpenHatch
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from mysite.search.models import *
project_name2lang = {u'Dasher': '',
 u'Epiphany': 'C',
 u'Evince': 'C',
 u'Evolution': 'C',
 u'Evolution Exchange': 'C',
 u'Evolution Webcal': 'C',
 u'Evolution-Data-Server': 'C',
 u'GIMP': 'C',
 u'GStreamer': 'C',
 u'GTK+': 'C',
 u'Glom': '',
 u'GnuCash': 'C',
 u'Gnumeric': '',
 u'GtkHtml': 'C',
 u'Gucharmap': '',
 u'JHBuild': 'shell script',
 u'NetworkManager': 'C',
 u'Pango': 'C',
 u'Rhythmbox': 'C',
 u'Tomboy': 'C#',
 u'Tracker': 'C',
 u'Vte': 'C',
 u'Yelp': 'C',
 u'anjuta': 'C',
 u'at-spi': 'C',
 u'atk': '',
 u'atomix': '',
 u'balsa': 'C',
 u'banshee': 'C#',
 u'brasero': '',
 u'conduit': '',
 u'conglomerate': '',
 u'damned-lies': '',
 u'deskbar-applet': 'Python',
 u'devilspie': '',
 u'dia': 'C',
 u'doxygen': '',
 u'ekiga': '',
 u'empathy': 'C',
 u'f-spot': '',
 u'file-roller': 'C',
 u'galeon': 'C',
 u'gcalctool': 'C',
 u'gconf-editor': 'C',
 u'gedit': 'C',
 u'general': '',
 u'gftp': 'C',
 u'gimp-web': '',
 u'glade3': '',
 u'glib': 'C',
 u'gnome-applets': 'C',
 u'gnome-bluetooth': '',
 u'gnome-commander': '',
 u'gnome-control-center': 'C',
 u'gnome-devel-docs': '',
 u'gnome-doc-utils': '',
 u'gnome-games': 'Python',
 u'gnome-launch-box': '',
 u'gnome-lirc-properties': '',
 u'gnome-media': '',
 u'gnome-nettool': '',
 u'gnome-packagekit': '',
 u'gnome-panel': 'C',
 u'gnome-phone-manager': 'C',
 u'gnome-pilot': '',
 u'gnome-scan': '',
 u'gnome-schedule': 'Python',
 u'gnome-screensaver': '',
 u'gnome-settings-daemon': 'C',
 u'gnome-shell': '',
 u'gnome-system-tools': 'C',
 u'gnome-terminal': 'C',
 u'gnome-themes': '',
 u'gnome-user-docs': '',
 u'gnome-user-share': 'C',
 u'gnome-utils': '',
 u'gnome-vfs': 'C',
 u'gok': '',
 u'gossip': '',
 u'gtkmozedit': '',
 u'gtksourceview': 'C',
 u'gvfs': 'C',
 u'libchamplain': '',
 u'libgnomeui': '',
 u'libgweather': '',
 u'lxml': '',
 u'metacity': 'C',
 u'nautilus': 'C',
 u'nautilus-sendto': '',
 u'planner': 'C',
 u'postr': '',
 u'seahorse': '',
 u'serpentine': 'Python',
 u'sound-juicer': 'C',
 u'totem': 'C',
 u'vinagre': '',
 u'xchat-gnome': ''}


for project_name, language in project_name2lang.iteritems():
    project = Project.objects.get(name=project_name)
    project.language = language
    project.save()
